name: Update GitHub Environments with Render Deployment

on:
  workflow_dispatch: # Для запуску вручну
  push:
    branches:
      - main # Тільки для основної гілки

jobs:
  update-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Notify GitHub Environments
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/deployments \
            -d '{
              "ref": "main",
              "task": "deploy",
              "auto_merge": false,
              "required_contexts": [],
              "environment": "production",
              "description": "Deployed to Render",
              "transient_environment": false
            }'


      - name: Trigger Render Deployment
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

      - name: Notify GitHub Environments
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/deployments \
            -d '{
              "ref": "main",
              "task": "deploy",
              "auto_merge": false,
              "required_contexts": [],
              "environment": "production",
              "description": "Deployed to Render",
              "transient_environment": false
            }'
